@ECHO OFF

rem Tindetheus
set TINDETHEUS_MODEL_DIR=20170512-110547
set TIDETHEUS_IMAGE_BATCH=1000
set TINDETHEUS_DISTANCE=5
set TINDETHEUS_LIKES=100
set TINDETHEUS_RETRIES=20

rem Tinder
set TINDER_AUTH_TOKEN=TODO

rem Facebook
set FACEBOOK_AUTH_TOKEN=TODO